spring:
  application:
    name: candidate-profile-transformer

logging:
  level:
    root: INFO
    com.candidate.transformer: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
